services:
    db:
        image: postgres:13
        hostname: barber-shop-db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    api:
        image: python:3.12
        hostname: barber-shop-api
        restart: always
        depends_on:
            db:
                condition: service_healthy
                restart: true
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
            - FRONTEND_HOST=${FRONTEND_HOST}
networks:
    barber-shop-network:
        external: true