services:

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
            - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
            - KEYCLOAK_API_SECRET=${KEYCLOAK_API_SECRET}
            - KEYCLOAK_FRONT_END_SECRET=${KEYCLOAK_FRONT_END_SECRET}
        volumes:
            - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
        command: ["start-dev", "--import-realm"]

    db:
        image: mysql:latest
        hostname: barbershop
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: barbershop
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 5
        env_file:
            - .env
        volumes:
            - ./db-dump:/docker-entrypoint-initdb.d
        
    api:
        image: python:3.12
        hostname: barber-shop-api
        restart: always
        depends_on:
            db:
                condition: service_healthy
                restart: true
        env_file:
            - .env
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DB=${MYSQL_DB}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=db
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
            - FRONTEND_HOST=${FRONTEND_HOST}
networks:
    barber-shop-network:
        external: true